version: '3.3'

# This is a mirror of the normal docker-compose but with a built-in-built.

services:
  guided-mt-code2vec:
    build:
      context: ""
      dockerfile: Dockerfile
      args:
        Guided-MT-Code2Vec_VERSION: 1.0-SNAPSHOT
    image: ciselab/guided-mt-code2vec:latest
    volumes:
      - ./compose_output:/app/Guided-MT-Code2Vec/genetic_output
      - ./src/test/resources/code_files:/app/Guided-MT-Code2Vec/genetic_input
    environment:
      target: /app/Guided-MT-Code2Vec/genetic_input
      output: /app/Guided-MT-Code2Vec/genetic_output
      configfile: /config/config.properties